### PR TITLE
Systemd template fix

### PR DESCRIPTION
**Pull request by timurb**
This pull request:
* fixes an issue in https://github.com/ddollar/foreman/issues/664
* adds a simple regression test for that
* reverts pull request https://github.com/ddollar/foreman/pull/652 as I believe it is not a good way to go (see explanation in my comment in #652)
* adds quoting of env variables as was suggested in #652 

If you think I should keep changes of #652 please let me know and I'll update my pull request.

### CODE REVIEW

**Comment by brandonhilkert** [comment]
This got me today too. Any chance this will be in a release soon? :)

**Comment by gammons** [comment]
This bit me as well.  The resulting output from a `foreman export` for systemd currently results in this:

```
ubuntu@ip-172-30-0-10:/etc/systemd/system/convertkit-web.target.wants$ cat convertkit-web@5000.service
[Unit]
PartOf=convertkit-web.target

[Service]
User=ubuntu
WorkingDirectory=/home/ubuntu/ck-geolocator
Environment=PORT=%i
Environment="RAILS_ENV=production" ExecStart=/bin/bash -lc 'bundle exec puma -C config/puma.rb'
Restart=always
StandardInput=null
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=%n
KillMode=mixed
TimeoutStopSec=5
```

Notice that `ExecStart` is on the same line as the `Environment` line.

**Comment by brandonhilkert** [comment]
@gammons I ended up using version `0.81.0` and that resolved the above. You do the same?

**Comment by gammons** [comment]
Yes, bumping down to `0.81.0` worked for me as well.

**Comment by ddollar** [comment]
Please rebase this and I'll merge, thanks!

**Comment by timurb** [comment]
@ddollar done

**Comment by ddollar** [comment]
Thanks!

**Pull request merged**
