### PR TITLE
updates rubies in travis

### PR DESCRIPTION
**Pull request by LeFnord**
- ensures only running with PID would be killed

last one is very rare, but possible 😉

### CODE REVIEW

**Comment by shinnn** [comment]
Conflicted with https://github.com/ddollar/foreman/commit/43a783372a3e9aaf32ffd3d21898ac2fd0547a55.

**Comment by LeFnord** [comment]
rebased against master

**Comment by LeFnord** [comment]
@shinnn … done

**Comment by LeFnord** [comment]
@shinnn … updated travis ruby versions again, and squashed commits 😉

**Comment by LeFnord** [comment]
@shinnn … are there any reasons not to mörge it?

**Pull request merged**
