### PR TITLE
Add reason for why developers might not include in Gemfile

### PR DESCRIPTION
**Pull request by abraham**
It seems the message has changed over the years but originally stems from [this comment](https://github.com/ddollar/foreman/pull/437#issuecomment-41110303). Instead of flatley rejecting the idea, specify why dev might want to avoid it so they can decide for themselves.

### CODE REVIEW

**Comment by abraham** [comment]
Fixed

**Comment by keithbro** [comment]
I also agree it would be useful to provide some context. But even with this PR - I'm still not clear on the risk of adding to the Gemfile. Would it be possible to get some further explanation please?

**Comment by ddollar** [comment]
I highly suggest that you do not include `foreman` in your Gemfile. I've written up my reasoning here:

https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman

**Comment by abraham** [comment]
That doesn't resolve the purpose of this PR but 🤷.

**Comment by ddollar** [comment]
Added the link to the README here: https://github.com/ddollar/foreman/commit/14bf2532500849ab076cb7512f05a32f815361d6

**Pull request closed without merging**
