### PR TITLE
Inline Thor dependency.

### PR DESCRIPTION
**Pull request by botandrose**
Got something working here pretty quickly. A few rough edges may need to be sanded down, but the overall premise seems workable.

### CODE REVIEW

**Comment by botandrose** [comment]
@ddollar Okay, had to monkeypatch the thor vendoring task from automatiek a bit to get it to bring thor's gemspec along so we can bundle it for vulnerability scans, but all appears well here. I'd like to try to push this gemspec vendoring functionality down into automatiek, rather than monkeypatching it at this level, but I think this is more or less done, from a technical standpoint. What do you think?

**Comment by ddollar** [comment]
Is it necessary to bundle thor's gemspec? It seems like having `thor` in the Gemfile will pull it and all of its dependencies into foreman's Gemfile.lock where they will trigger appropriate vulnerability notifications.

**Comment by botandrose** [comment]
Ah, so you're suggesting that we vendor Thor under Foreman::Thor (as it is in this PR), but instead of pointing bundler at that vendored version for vulnerability analysis, we bundle real-deal Thor in addition?

**Comment by botandrose** [comment]
FWIW, Thor has no dependencies, which makes all this simpler

**Comment by ddollar** [comment]
Cool, sounds like you can probably unwind the monkey patching of the vendoring then and we'll just vendor thor and let vulnerability notifications come from the entry in the Gemfile.lock

**Comment by botandrose** [comment]
Roger that. Easy peasy!

**Comment by botandrose** [comment]
@ddollar Done. Take a look and let me know what you think!

**Comment by ddollar** [comment]
Looking good, will take a look this evening around building a new gem version

**Comment by ddollar** [comment]
Released as 0.86.0

**Comment by botandrose** [comment]
And we're running it in production, and it works! Thank you so much, @ddollar!

**Comment by ddollar** [comment]
Thanks for the PR :)

**Pull request merged**
