### PR TITLE
Update ruby versions to latest in Travis and update Thor to latest version in Gemfile

### PR DESCRIPTION
**Pull request by Jesterovskiy**

### CODE REVIEW

**Comment by ddollar** [comment]
I would accept an update to the Ruby versions but updating the thor dependency would put it out of sync with the vendored thor.

**Comment by Jesterovskiy** [comment]
@ddollar ok, I'll revert Thor changes, one moment

**Comment by ddollar** [comment]
Please update this PR to be only an update to the Ruby versions and I would be happy to merge. Thanks!

**Comment by Jesterovskiy** [comment]
@ddollar done! Sorry for a big delay)

**Comment by Jesterovskiy** [comment]
@ddollar do you have time to review it again?)

**Comment by kkohrt** [comment]
@ddollar & @Jesterovskiy -- There is a ruby 2.7.2 out there, https://www.ruby-lang.org/en/downloads/releases/
But I think it would be great to get a least one 2.7.* test merged in, yes?
Anything I can do to help?

**Comment by micwoj92** [comment]
There is even ruby 3.0 now :o 
does anyone know if this is ruby 3 compatible?

**Comment by Jesterovskiy** [comment]
@kkohrt @micwoj92 almost a year ago I made my changes but @ddollar gone somewhere =(

**Comment by Jesterovskiy** [comment]
I think, I can close it now, because nobody cares

**Pull request closed without merging**
