### PR TITLE
Support for passing multiple processes to foreman start

### PR DESCRIPTION
**Pull request by arcz**
It is compatible with previous syntax. Now you can pass couple of them instead one.

### CODE REVIEW

**Comment by ddollar** [comment]
I'm OK with this change but would you please add some test coverage and update the manual in the appropriate places as well.

**Comment by arcz** [comment]
I've added missing test and documentation. I hope it is ok :smiley:

**Comment by arcz** [comment]
Failing build seems to be related to race condition in other test

**Comment by ArtemPyanykh** [comment]
That would come in :+1: Do you have any plans on finishing this?

**Comment by Chronial** [comment]
Note that this is allready possible with `foreman start web=2,worker=1`.

**Comment by ddollar** [comment]
Sorry for the long delay but I'm trying to get foreman back into shape with maintenance. Please rebase your PR and reopen it once you do. Thank you!

**Pull request closed without merging**
