### PR TITLE
rails 6 compatibility

### PR DESCRIPTION
**Pull request by montanalow**

### CODE REVIEW

**Comment by mogox** [comment]
Hello @ddollar, is there anything else needed for this PR to be merged?  I'd be great to have it before Rails 6 is fully released

**Comment by chrismo** [comment]
I emailed David with the email account on his homepage asking him to look at this if he can. It's possible he's not seeing the GitHub notifications (I know I get a zillion and never see things like this on old repos).

**Comment by chrismo** [comment]
See also #737

**Comment by chrismo** [comment]
Looks like a dupe of #727

**Comment by ddollar** [comment]
I highly suggest that you do not include `foreman` in your Gemfile. I've written up my reasoning here:

https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman

**Pull request closed without merging**
